name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install and cache APT packages
      # You may pin to the exact commit or the version.
      # uses: gerlero/apt-install@c0fa73fe5c4a22deecf6d629565be92a15dd2026
      uses: gerlero/apt-install@v1.3.12
      with:
        # APT packages to install
        packages: libsdl2-dev
    - uses: actions/checkout@v4
    - name: autoreconf
      run: autoreconf -fi
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make test
      run: make test
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        # Artifact name. If the `archive` input is `false`, the name of the file uploaded will be the artifact name.
        name: main_6502
        # A file, directory or wildcard pattern that describes what to upload.
        path: bin/main_6502
        # The desired behavior if no files are found using the provided path.
        overwrite: true
   
    
